theme = "plain"
icons = "awesome"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "net"
ssid = true
ip = true
device = "wlp0s20f3"
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "net"
ip = true
device = "enp0s31f6"
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "time"
interval = 5
format = "%a %Y-%m-%d %H:%M:%S"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"
